Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabProject.Models;
using System.Drawing.Printing;

namespace LabProject.Controllers
{
    public class OrdersController : Controller
    {
        private readonly dbLabContext _context;

        public OrdersController(dbLabContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            int pageSize = 10; // 每頁顯示的資料數量
            var totalItems = await _context.Orders.CountAsync(); // 總資料數
            // 查詢並應用分頁
            var orders = await _context.Orders
                .Include(o => o.Employee) // 包含關聯的 Employee 資料
                .OrderByDescending(o => o.OrderDate)
                .ThenByDescending(o => o.OrderID)
                .Skip((pageNumber - 1) * pageSize) // 跳過前面的資料
                .Take(pageSize) // 取得當前頁的資料
                .ToListAsync(); // 轉換為列表

            // 將資料傳遞到 View
            ViewBag.Orders = orders; // 當前頁的訂單資料
            ViewBag.CurrentPage = pageNumber; // 當前頁碼
            ViewBag.TotalPages = (int)Math.Ceiling((decimal)totalItems / pageSize); // 總頁數
            return View(orders);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Employee)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                ViewData["ErrorMessage"] = "訂單不存在";
                return View(orders);
            }

            if (orders.Status)
            {
                ViewData["ErrorMessage"] = "已完成的訂單無法刪除";
                return View(orders);
            }

            _context.Orders.Remove(orders);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdersExists(int id)
        {
            return _context.Orders.Any(e => e.OrderID == id);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteChemicalOrderDetails(int orderId, int chemicalId)
        {
            var chemicalOrderDetails = await _context.ChemicalOrderDetails.FindAsync(orderId, chemicalId);
            if (chemicalOrderDetails != null)
            {            
                _context.ChemicalOrderDetails.Remove(chemicalOrderDetails);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Delete", new { id = orderId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConsumableOrderDetails(int orderId, int consumableId)
        {
            var consumableOrderDetails = await _context.ConsumableOrderDetails.FindAsync(orderId, consumableId);
            if (consumableOrderDetails != null)
            {
                _context.ConsumableOrderDetails.Remove(consumableOrderDetails);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Delete", new { id = orderId });
        }

    }
}

Controllers/SamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabProject.Models;

namespace LabProject.Controllers
{
    public class SamplesController : Controller
    {
        private readonly dbLabContext _context;

        public SamplesController(dbLabContext context)
        {
            _context = context;
        }

        // GET: Samples
        public async Task<IActionResult> Index()
        {
            var dbLabContext = _context.Samples.Include(s => s.SampleType).OrderBy(s =>s.SampleName).ThenBy(s=>s.SampleType);
            return View(await dbLabContext.ToListAsync());
        }

        // GET: Samples/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var samples = await _context.Samples
                .Include(s => s.SampleType)
                .FirstOrDefaultAsync(m => m.SampleID == id);
            if (samples == null)
            {
                return NotFound();
            }

            return View(samples);
        }

        // POST: Samples/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var samples = await _context.Samples.FindAsync(id);
            if (samples != null)
            {
                _context.Samples.Remove(samples);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //增加刪除使用紀錄Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteSampleRecord(int id)
        {
            var sampleRecord = await _context.SampleRecords.FindAsync(id);
            
            if (sampleRecord != null)
            {
                var sample = await _context.Samples.FirstOrDefaultAsync(s => s.SampleID == sampleRecord.SampleID);
                if (sample == null)
                {
                    return NotFound();
                }
                if (sampleRecord.TransactionType)
                {
                    sample.Quantity -= sampleRecord.Quantity;
                }
                else { sample.Quantity += sampleRecord.Quantity; }
               
                _context.Samples.Update(sample);
                _context.SampleRecords.Remove(sampleRecord);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Delete", new { id = sampleRecord.SampleID });
        }

        private bool SamplesExists(long id)
        {
            return _context.Samples.Any(e => e.SampleID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var Manager = Context.Session.GetString("Manager");

    if (Manager == null)
    {
        Context.Response.Redirect("/Home/Index");
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 實驗室管理系統</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LabProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 fw-bold">
            <div class="container-fluid">
                <span class="navbar-brand"><img src="/photo/logo.png" class="h-5" />實驗室管理系統</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Samples" asp-action="Index">樣本管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="SampleTypes" asp-action="Index">樣本類別管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Chemicals" asp-action="Index">化學品管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">化學品種類管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Consumables" asp-action="Index">耗材管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Suppliers" asp-action="Index">供應商管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Orders" asp-action="Index">訂單管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Employees" asp-action="Index">會員資料管理</a>
                        </li>
                    </ul>
                </div>
                <a asp-controller="Home" asp-action="Logout" class="btn btn-info text-black" onclick="return confirm('確定登出嗎?')">登出</a>
            </div>
        </nav>
    </header>
    <div class="container p-0 pb-1">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-gray">
        <div class="container">
            Copyright &copy; @DateTime.Now.Year - 實驗室管理系統 - <a asp-area="" asp-controller="Home" asp-action="Privacy">隱私權政策</a> @DateTime.Now 更新
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
@{
    var Manager = Context.Session.GetString("Manager");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 實驗室管理系統</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LabProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark bg-img border-bottom box-shadow">
            <div class="container-fluid fw-bold">               
                    <span class="navbar-brand"><img src="/photo/logo.png" class="h-5" />實驗室管理系統</span>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="PostSamples" asp-action="Index">樣本資料</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="PostChemicals" asp-action="Index">化學品資料</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="PostConsumables" asp-action="Index">耗材資料</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="PostSuppliers" asp-action="Index">供應商資料</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="PostOrders" asp-action="Index">訂單資料</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">隱私權</a>
                            </li>
                        </ul>
                    </div>
                    @if(Manager != null){
                 <a asp-action="Logout" asp-controller="Home" class="btn btn-outline-light">登出</a>
                }
            </div>
        </nav>
    </header>

    <div class="container-fluid p-0">
        <main role="main">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted bg-gray">
        <div class="container">
            Copyright &copy; @DateTime.Now.Year - 實驗室管理系統 - <a asp-area="" asp-controller="Home" asp-action="Privacy">隱私權政策</a> @DateTime.Now 更新
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>